"""
AFRB Dataset Loader.

Reads an AFRB-schema CSV (the original Asset Failure Root-cause Behaviour data
*or* the synthetic CSV generated by ``data_generator``), converts every row to
the shared ``CanonicalRecord`` schema and to embedding documents.

Changes vs. the original loader
-------------------------------
* Missing numeric values are **no longer imputed with the column median** —
  imputation fabricated sensor readings that agents then cited as facts.
  Missing values stay ``None`` and are written as "unavailable" in text.
* Document metadata now carries the canonical fields (record_id, label,
  equipment type, sensors, source_type …).  The original metadata only held
  ``{"source": "afrb"}`` because none of the expected keys existed in the CSV.
* Provenance columns of synthetic data (source_type, synthetic_scenario …) are
  kept in metadata but never embedded as evidence text.
"""

import re
from pathlib import Path
from typing import Dict, List, Optional

import pandas as pd

from harness.canonical import CanonicalRecord, afrb_row_to_record, normalise_column
from utils.logger import setup_logger

logger = setup_logger(__name__)


class AFRBLoader:
    """Loads an AFRB-schema CSV and converts it to canonical records/documents."""

    def __init__(self, csv_path: str, default_source_type: str = "real"):
        self.csv_path = Path(csv_path)
        self.default_source_type = default_source_type
        if not self.csv_path.exists():
            raise FileNotFoundError(f"AFRB CSV not found at: {self.csv_path}")
        self.columns: List[str] = []
        self.quality: Dict = {}

    # ── Preprocessing ────────────────────────────────────────────────────────

    def _preprocess(self, df: pd.DataFrame) -> pd.DataFrame:
        """Clean and normalise the dataframe WITHOUT inventing values."""
        df.columns = [normalise_column(c) for c in df.columns]
        df = df.dropna(axis=1, how="all").dropna(axis=0, how="all")
        for col in df.columns:
            if df[col].dtype == object or str(df[col].dtype).startswith("str"):
                df[col] = df[col].where(df[col].isna(), df[col].astype(str).str.strip())
        if "source_type" not in df.columns:
            df["source_type"] = self.default_source_type
        self.quality = {
            "rows": int(len(df)),
            "columns": int(len(df.columns)),
            "missing_values": int(df.isna().sum().sum()),
            "duplicate_rows": int(df.duplicated().sum()),
        }
        logger.info("Preprocessed AFRB (%s): %d rows × %d cols, %d missing cells kept as missing",
                    self.csv_path.name, len(df), len(df.columns), self.quality["missing_values"])
        return df

    # ── Public ───────────────────────────────────────────────────────────────

    def load_records(self, dataset_name: str = "afrb") -> List[CanonicalRecord]:
        logger.info("Loading AFRB CSV from: %s", self.csv_path)
        df = pd.read_csv(self.csv_path, low_memory=False)
        df = self._preprocess(df)
        cols = [c for c in df.columns]
        self.columns = cols
        rows = df.astype(object).where(df.notna(), None).to_dict("records")
        records = [afrb_row_to_record(r, cols, dataset=dataset_name) for r in rows]
        logger.info("Loaded %d canonical AFRB records (%s).", len(records), self.csv_path.name)
        return records

    def load(self) -> List[Dict]:
        """Backward-compatible API: [{content, metadata}, ...]"""
        return [record_to_document(r) for r in self.load_records()]


def record_to_document(r: CanonicalRecord) -> Dict:
    meta: Dict = {
        "source": r.dataset,
        "record_id": r.record_id,
        "source_type": r.source_type,
        "failure_mode": r.label,
        "equipment_type": r.equipment_type,
        "system_context": r.system_context,
    }
    if r.synthetic_scenario:
        meta["synthetic_scenario"] = r.synthetic_scenario
    return {"content": r.text, "metadata": meta}
